// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PhoenixContext))]
    [Migration("20231115163946_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Domain.AgedTransactionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Rule identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasComment("The UTC date when the rule was created.");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasComment("The UTC date when the rule was updated.");

                    b.Property<int?>("HighRange")
                        .HasColumnType("int")
                        .HasComment("The max value of days to apply the rule.");

                    b.Property<int>("LowRange")
                        .HasColumnType("int")
                        .HasComment("The min value of days to apply the rule.");

                    b.Property<string>("TransferStatusId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasComment("The transfer status to be applied.");

                    b.HasKey("Id");

                    b.ToTable("AgedTransactionSettings", (string)null);

                    b.HasComment("Stores the rules to grow old the transactions automatically");
                });

            modelBuilder.Entity("Core.Domain.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("The transaction's identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)")
                        .HasComment("The Transaction's amount.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasComment("The UTC Date the transaction was created at.");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Unique transaction number created by the system.");

                    b.Property<string>("TransferStatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Status of the transaction.");

                    b.HasKey("Id");

                    b.HasIndex("TransactionNumber")
                        .IsUnique();

                    b.ToTable("Transaction", (string)null);

                    b.HasComment("Stores Information related with Transactions.");
                });

            modelBuilder.Entity("Core.Domain.TransactionStatusChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("History entry identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of the change.");

                    b.Property<string>("StatusAfterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Current transfer status.");

                    b.Property<string>("StatusBeforeId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasComment("Transfer status before the change.");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint")
                        .HasComment("Transaction the history entry belongs to.");

                    b.HasKey("Id");

                    b.ToTable("TransactionStatusChange", (string)null);

                    b.HasComment("Stores Transaction Status Changes History.");
                });
#pragma warning restore 612, 618
        }
    }
}
